# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 370529a9c50533d161a171c973eb7d4047ec367e3c88cf15893cfd49c42a9ff028d6198318bac115644c2a70be96137e8b003401cc37df886245960487fac45a

test:
  secret_key_base: 963ac920e8bd2fc4f7da457cb5727356ac742e692faebf1fb505c1fcc38a732d6c87603bd9311d2ec0926452f4079fb48db016d6260537a6dcdf84dc58e3b431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
